import React, { useState } from 'react';
import { 
  FileText, 
  Download, 
  Printer, 
  Bookmark, 
  CheckCircle2, 
  ShieldCheck, 
  TrendingUp, 
  ShieldAlert, 
  Calendar, 
  Clock, 
  ArrowLeft,
  Sparkles,
  Loader2
} from 'lucide-react';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { SimulationResult } from '../types';

interface ReportPageProps {
  simulation: SimulationResult;
  selectedScenarioId?: string;
  onBackToSimulations: () => void;
  onSaveToLibrary: (sim: SimulationResult) => void;
  darkMode: boolean;
}

export const ReportPage: React.FC<ReportPageProps> = ({
  simulation,
  selectedScenarioId,
  onBackToSimulations,
  onSaveToLibrary,
  darkMode,
}) => {
  const scenario = simulation.scenarios.find((s) => s.id === selectedScenarioId) || simulation.scenarios[0];
  const [completedTasks, setCompletedTasks] = useState<Record<string, boolean>>({});
  const [isSaved, setIsSaved] = useState(false);
  const [isGeneratingPDF, setIsGeneratingPDF] = useState(false);
  const [notificationMsg, setNotificationMsg] = useState<string | null>(null);

  const toggleTask = (key: string) => {
    setCompletedTasks((prev) => ({ ...prev, [key]: !prev[key] }));
  };

  const handleExportPDF = async () => {
    const element = document.getElementById('report-document-container');
    if (!element) return;

    setIsGeneratingPDF(true);
    setNotificationMsg('Generating downloadable PDF report...');

    try {
      const canvas = await html2canvas(element, {
        scale: 2,
        useCORS: true,
        logging: false,
        backgroundColor: darkMode ? '#0B1120' : '#ffffff',
      });

      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = pdf.internal.pageSize.getHeight();

      const margin = 10;
      const contentWidth = pdfWidth - margin * 2;
      const contentHeight = (canvas.height * contentWidth) / canvas.width;

      let heightLeft = contentHeight;
      let position = margin;

      pdf.addImage(imgData, 'PNG', margin, position, contentWidth, contentHeight);
      heightLeft -= (pdfHeight - margin * 2);

      while (heightLeft > 0) {
        position = heightLeft - contentHeight + margin;
        pdf.addPage();
        pdf.addImage(imgData, 'PNG', margin, position, contentWidth, contentHeight);
        heightLeft -= (pdfHeight - margin * 2);
      }

      const cleanTitle = simulation.goalDetails.title.replace(/[^a-zA-Z0-9_]/g, '_');
      pdf.save(`FutureEngine_Report_${cleanTitle}.pdf`);
      setNotificationMsg('PDF downloaded successfully!');
      setTimeout(() => setNotificationMsg(null), 4000);
    } catch (err) {
      console.error('PDF generation error:', err);
      setNotificationMsg('Failed to render PDF canvas. Downloading Markdown instead...');
      handleDownloadMarkdown();
      setTimeout(() => setNotificationMsg(null), 4000);
    } finally {
      setIsGeneratingPDF(false);
    }
  };

  const handlePrint = async () => {
    try {
      // Attempt native window print
      window.print();
    } catch (e) {
      console.warn('window.print failed (sandboxed iframe), falling back to PDF download:', e);
      setNotificationMsg('Print modal restricted in preview. Generating PDF download instead...');
      await handleExportPDF();
    }
  };

  const handleDownloadMarkdown = () => {
    const markdown = `# Future Engine Decision Report: ${simulation.goalDetails.title}
Date: ${new Date(simulation.createdAt).toLocaleDateString()}

> DISCLAIMER: ${simulation.disclaimer}

## Executive Summary
${simulation.overallAnalysis}

## Primary Selected Scenario: ${scenario.title} (${scenario.strategyType})
Tagline: ${scenario.tagline}
Summary: ${scenario.summary}

### Future Decision Framework (FDF) Scores
- Goal Score: ${scenario.fdfScores.goalScore} / 100
- Risk Score: ${scenario.fdfScores.riskScore} / 100
- Opportunity Score: ${scenario.fdfScores.opportunityScore} / 100
- Confidence Level: ${scenario.fdfScores.confidenceLevel}
- Confidence Reasoning: ${scenario.fdfScores.confidenceReasoning}

### Advantages
${scenario.advantages.map((a) => `- ${a}`).join('\n')}

### Disadvantages
${scenario.disadvantages.map((d) => `- ${d}`).join('\n')}

### Key Risks
${scenario.risks.map((r) => `- ${r}`).join('\n')}

### Upside Opportunities
${scenario.opportunities.map((o) => `- ${o}`).join('\n')}

### Phased Execution Roadmap
${simulation.roadmap
  .map(
    (p) => `#### ${p.phase}
Milestone: ${p.milestone}
Actions:
${p.actions.map((a) => `  * [ ] ${a}`).join('\n')}
`
  )
  .join('\n')}

---
Generated by Future Engine AI Decision Simulation Platform
`;

    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `FutureEngine_Report_${simulation.id}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleSave = () => {
    onSaveToLibrary(simulation);
    setIsSaved(true);
    setTimeout(() => setIsSaved(false), 3000);
  };

  return (
    <div className="max-w-5xl mx-auto px-4 py-8 print:p-0 print:max-w-none">
      
      {/* Non-printable Action Bar */}
      <div className="print:hidden mb-6 flex flex-wrap items-center justify-between gap-4">
        <button
          onClick={onBackToSimulations}
          className="flex items-center space-x-2 text-xs font-semibold text-slate-400 hover:text-white transition-colors"
        >
          <ArrowLeft className="w-4 h-4" />
          <span>Back to All Simulations</span>
        </button>

        <div className="flex flex-wrap items-center gap-2">
          <button
            onClick={handleSave}
            className={`flex items-center space-x-1.5 px-3.5 py-2 rounded-xl text-xs font-semibold border transition-all ${
              isSaved
                ? 'bg-emerald-500/20 text-emerald-400 border-emerald-500/30'
                : darkMode
                  ? 'bg-slate-800 text-slate-200 border-slate-700 hover:bg-slate-700'
                  : 'bg-white text-slate-700 border-slate-300 hover:bg-slate-50'
            }`}
          >
            <Bookmark className="w-3.5 h-3.5" />
            <span>{isSaved ? 'Saved in Library' : 'Save Report'}</span>
          </button>

          <button
            onClick={handleDownloadMarkdown}
            className={`flex items-center space-x-1.5 px-3.5 py-2 rounded-xl text-xs font-semibold border transition-all ${
              darkMode
                ? 'bg-slate-800 text-slate-200 border-slate-700 hover:bg-slate-700'
                : 'bg-white text-slate-700 border-slate-300 hover:bg-slate-50'
            }`}
          >
            <Download className="w-3.5 h-3.5" />
            <span>Export Markdown</span>
          </button>

          <button
            onClick={handleExportPDF}
            disabled={isGeneratingPDF}
            className={`flex items-center space-x-1.5 px-4 py-2 rounded-xl text-xs font-semibold text-white bg-indigo-600 hover:bg-indigo-500 transition-colors shadow-md disabled:opacity-60 disabled:cursor-not-allowed`}
          >
            {isGeneratingPDF ? (
              <Loader2 className="w-3.5 h-3.5 animate-spin" />
            ) : (
              <FileText className="w-3.5 h-3.5" />
            )}
            <span>{isGeneratingPDF ? 'Generating PDF...' : 'Save PDF'}</span>
          </button>

          <button
            onClick={handlePrint}
            className={`flex items-center space-x-1.5 px-3.5 py-2 rounded-xl text-xs font-semibold border transition-all ${
              darkMode
                ? 'bg-slate-800 text-slate-200 border-slate-700 hover:bg-slate-700'
                : 'bg-white text-slate-700 border-slate-300 hover:bg-slate-50'
            }`}
          >
            <Printer className="w-3.5 h-3.5" />
            <span>Print Report</span>
          </button>
        </div>
      </div>

      {/* Notification Banner */}
      {notificationMsg && (
        <div className="print:hidden mb-4 p-3 rounded-xl bg-indigo-500/15 border border-indigo-500/30 text-indigo-300 text-xs flex items-center justify-between">
          <span>{notificationMsg}</span>
          {isGeneratingPDF && <Loader2 className="w-3.5 h-3.5 animate-spin shrink-0" />}
        </div>
      )}

      {/* Report Document Container */}
      <div 
        id="report-document-container"
        className={`p-8 sm:p-12 rounded-3xl border shadow-2xl print:shadow-none print:border-none print:p-0 ${
          darkMode ? 'bg-[#0B1120] border-slate-800 text-slate-100' : 'bg-white border-slate-200 text-slate-900'
        }`}
      >

        
        {/* Report Header */}
        <div className="border-b border-slate-800 pb-8 mb-8">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-3">
              <div className="w-10 h-10 rounded-xl bg-indigo-600 text-white flex items-center justify-center font-black text-xl">
                FE
              </div>
              <div>
                <h1 className="text-xl font-bold tracking-tight text-white print:text-black">FUTURE ENGINE</h1>
                <p className="text-xs text-slate-400 print:text-slate-600">Decision Support Executive Report</p>
              </div>
            </div>
            <div className="text-right text-xs text-slate-400 print:text-slate-600">
              <div><strong>Date:</strong> {new Date(simulation.createdAt).toLocaleDateString()}</div>
              <div><strong>Report ID:</strong> {simulation.id}</div>
            </div>
          </div>

          {/* Mandatory Disclaimer Box */}
          <div className="mt-6 p-4 rounded-xl bg-slate-900 border border-slate-800 print:bg-slate-100 print:border-slate-300">
            <div className="flex items-center space-x-2 text-xs text-slate-300 print:text-slate-700">
              <ShieldCheck className="w-4 h-4 text-emerald-400 shrink-0" />
              <span><strong>System Disclaimer:</strong> {simulation.disclaimer}</span>
            </div>
          </div>
        </div>

        {/* Executive Summary */}
        <div className="mb-10">
          <h2 className="text-xl font-extrabold text-white print:text-black mb-3">1. Executive Summary & Goal Context</h2>
          <div className="p-5 rounded-2xl bg-slate-900/60 border border-slate-800 print:bg-slate-50 print:border-slate-200 space-y-3">
            <div>
              <span className="text-xs font-bold text-indigo-400 uppercase tracking-wider block">Decision Target</span>
              <h3 className="text-lg font-bold text-slate-100 print:text-slate-900">{simulation.goalDetails.title}</h3>
            </div>
            <p className="text-xs text-slate-300 print:text-slate-700 leading-relaxed">
              {simulation.overallAnalysis}
            </p>
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-4 pt-3 border-t border-slate-800 print:border-slate-300 text-xs">
              <div>
                <span className="text-slate-400 block">Target Timeframe</span>
                <span className="font-bold text-slate-200 print:text-slate-900">{simulation.goalDetails.targetTimeframe}</span>
              </div>
              <div>
                <span className="text-slate-400 block">Estimated Budget</span>
                <span className="font-bold text-slate-200 print:text-slate-900">{scenario.budgetEstimate}</span>
              </div>
              <div>
                <span className="text-slate-400 block">Primary Priority</span>
                <span className="font-bold text-slate-200 print:text-slate-900">{simulation.goalDetails.keyPriority}</span>
              </div>
            </div>
          </div>
        </div>

        {/* Selected Primary Pathway */}
        <div className="mb-10">
          <h2 className="text-xl font-extrabold text-white print:text-black mb-3">2. Evaluated Pathway: {scenario.title}</h2>
          
          {/* FDF Score Breakdown */}
          <div className="grid grid-cols-3 gap-4 mb-6">
            <div className="p-4 rounded-xl bg-indigo-500/10 border border-indigo-500/20 text-center">
              <span className="text-[11px] font-bold text-indigo-400 uppercase block">Goal Score</span>
              <span className="text-2xl font-black text-indigo-300">{scenario.fdfScores.goalScore}/100</span>
            </div>
            <div className="p-4 rounded-xl bg-amber-500/10 border border-amber-500/20 text-center">
              <span className="text-[11px] font-bold text-amber-400 uppercase block">Risk Score</span>
              <span className="text-2xl font-black text-amber-300">{scenario.fdfScores.riskScore}/100</span>
            </div>
            <div className="p-4 rounded-xl bg-emerald-500/10 border border-emerald-500/20 text-center">
              <span className="text-[11px] font-bold text-emerald-400 uppercase block">Opportunity Score</span>
              <span className="text-2xl font-black text-emerald-300">{scenario.fdfScores.opportunityScore}/100</span>
            </div>
          </div>

          <p className="text-xs text-slate-300 print:text-slate-700 leading-relaxed mb-4">
            {scenario.summary}
          </p>

          {/* Risk & Opportunity Matrix */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 my-6">
            
            <div className="p-5 rounded-2xl bg-red-500/5 border border-red-500/15">
              <h3 className="text-sm font-bold text-red-400 mb-3 flex items-center space-x-2">
                <ShieldAlert className="w-4 h-4" />
                <span>Risk Matrix</span>
              </h3>
              <ul className="space-y-2 text-xs text-slate-300 print:text-slate-700">
                {scenario.risks.map((r, i) => (
                  <li key={i} className="flex items-start space-x-2">
                    <span className="w-1.5 h-1.5 rounded-full bg-red-400 mt-1.5 shrink-0"></span>
                    <span>{r}</span>
                  </li>
                ))}
              </ul>
            </div>

            <div className="p-5 rounded-2xl bg-emerald-500/5 border border-emerald-500/15">
              <h3 className="text-sm font-bold text-emerald-400 mb-3 flex items-center space-x-2">
                <TrendingUp className="w-4 h-4" />
                <span>Opportunity Matrix</span>
              </h3>
              <ul className="space-y-2 text-xs text-slate-300 print:text-slate-700">
                {scenario.opportunities.map((o, i) => (
                  <li key={i} className="flex items-start space-x-2">
                    <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 mt-1.5 shrink-0"></span>
                    <span>{o}</span>
                  </li>
                ))}
              </ul>
            </div>

          </div>
        </div>

        {/* Phased Execution Roadmap */}
        <div className="mb-10">
          <h2 className="text-xl font-extrabold text-white print:text-black mb-4">3. Phased Execution Roadmap</h2>
          <div className="space-y-4">
            {simulation.roadmap.map((phase, pIdx) => (
              <div
                key={pIdx}
                className="p-5 rounded-2xl bg-slate-900/60 border border-slate-800 print:bg-slate-50 print:border-slate-200"
              >
                <div className="flex items-center justify-between mb-2">
                  <h3 className="text-sm font-bold text-indigo-400 print:text-indigo-600">{phase.phase}</h3>
                  <span className="px-2.5 py-0.5 rounded-full text-[10px] font-semibold bg-indigo-500/10 text-indigo-300 border border-indigo-500/20">
                    Milestone: {phase.milestone}
                  </span>
                </div>

                <div className="space-y-2 mt-3">
                  {phase.actions.map((act, aIdx) => {
                    const taskKey = `${pIdx}-${aIdx}`;
                    const isChecked = completedTasks[taskKey];

                    return (
                      <div
                        key={aIdx}
                        onClick={() => toggleTask(taskKey)}
                        className={`flex items-center space-x-3 p-2.5 rounded-xl border text-xs cursor-pointer transition-all ${
                          isChecked
                            ? 'bg-emerald-500/10 border-emerald-500/30 text-emerald-300 line-through'
                            : 'bg-slate-950/40 border-slate-800 text-slate-200 hover:border-slate-700'
                        }`}
                      >
                        <div className={`w-4 h-4 rounded border flex items-center justify-center shrink-0 ${
                          isChecked ? 'bg-emerald-500 border-emerald-500 text-slate-950' : 'border-slate-600'
                        }`}>
                          {isChecked && <CheckCircle2 className="w-3 h-3" />}
                        </div>
                        <span>{act}</span>
                      </div>
                    );
                  })}
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Confidence Notes & Assumptions */}
        <div className="p-5 rounded-2xl bg-purple-500/5 border border-purple-500/15 text-xs text-slate-300 print:text-slate-700">
          <h3 className="font-bold text-purple-400 mb-1">Confidence Rating & Modeling Assumptions</h3>
          <p>
            <strong>Rating: {scenario.fdfScores.confidenceLevel} Confidence.</strong> {scenario.fdfScores.confidenceReasoning}
          </p>
        </div>

      </div>

    </div>
  );
};
